application: gk698ostprojectfinalv3
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: OST.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
